apiVersion: v1
kind: Namespace
metadata:
  name: voting-app
  labels:
    name: voting-app
    tier: application
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: voting-app
type: Opaque
data:
  # Base64 encoded values
  # admin:password123
  username: YWRtaW4=
  password: cGFzc3dvcmQxMjM=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: voting-app
data:
  DATABASE_NAME: "voting_app"
  ENVIRONMENT: "production"
  JWT_SECRET_KEY: "your-super-secret-jwt-key-for-production"